### ISSUE TITLE
App user has no access to nltk data

### ISSUE THREAD

**Issue by stlozhaw** [sustainability-zhaw/sdg-indexer#11]
nltk data downloaded by `root` user during image build is not accessible by `app` user.

**Comment by phish108** [comment]
Wouldn't it make more sense to install all requirements as the user imstead of root to set the permissions from the start?

In the conda/mamba world there is a fix permissions command, which fails with pip. I saw a bunch of comments that point towards user installs. 

This would move the `USER` command to the very top. 

What do you think?

**Comment by stlozhaw** [comment]
I don't agree with installing packages as the app user. Currently I am not seeing what problem it would solve.
The goal is not to set up the system exclusively for the app user and make things only available to it. The reason to run as a less privileged user is for security reasons. 

Additionally, this would make working more difficult as I am developing inside the container with VS Code. Packages and data would have to be installed again for the root user or somehow made available to the root user.
